import { StyleSheet } from 'react-native';
import { COLORS, FLOATING_SHADOW, SOFT_SHADOW } from '../constants/theme';

export const styles = StyleSheet.create({
  app: {
    flex: 1,
    backgroundColor: COLORS.background,
  },
  backgroundAura: {
    ...StyleSheet.absoluteFill,
    pointerEvents: 'none',
    overflow: 'hidden',
  },
  backgroundBlobTop: {
    position: 'absolute',
    top: -95,
    right: -85,
    width: 260,
    height: 260,
    borderRadius: 130,
    backgroundColor: '#DCEBFF',
    opacity: 0.9,
  },
  backgroundBlobMiddle: {
    position: 'absolute',
    top: 245,
    left: -120,
    width: 265,
    height: 265,
    borderRadius: 133,
    backgroundColor: '#FFE5EE',
    opacity: 0.78,
  },
  backgroundBlobBottom: {
    position: 'absolute',
    right: -105,
    bottom: 95,
    width: 245,
    height: 245,
    borderRadius: 123,
    backgroundColor: '#E8FBF4',
    opacity: 0.72,
  },
  safeArea: {
    flex: 1,
    backgroundColor: 'transparent',
  },
  screen: {
    flex: 1,
  },
  loadingScreen: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.background,
  },
  logoBadge: {
    width: 66,
    height: 66,
    borderRadius: 24,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.purple,
    ...FLOATING_SHADOW,
  },
  loadingTitle: {
    marginTop: 18,
    color: COLORS.ink,
    fontSize: 28,
    fontWeight: '900',
    letterSpacing: -0.8,
    textAlign: 'center',
  },
  loadingText: {
    maxWidth: 310,
    marginTop: 12,
    color: COLORS.muted,
    fontSize: 15,
    fontWeight: '700',
    lineHeight: 22,
    textAlign: 'center',
  },
  appNotice: {
    marginHorizontal: 20,
    marginTop: 8,
    marginBottom: 8,
    padding: 12,
    borderRadius: 16,
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
    backgroundColor: COLORS.bluePale,
    borderWidth: 1,
    borderColor: '#DCE7FF',
  },
  appNoticeText: {
    flex: 1,
    color: '#5268C9',
    fontSize: 12,
    lineHeight: 17,
    fontWeight: '700',
  },
  appNoticeClose: {
    width: 24,
    height: 24,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.white,
  },
  syncNotice: {
    alignSelf: 'center',
    marginTop: 8,
    marginBottom: 8,
    paddingHorizontal: 13,
    paddingVertical: 9,
    borderRadius: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
    backgroundColor: COLORS.purplePale,
    borderWidth: 1,
    borderColor: '#E4DCFF',
  },
  syncNoticeText: {
    color: COLORS.purpleDark,
    fontSize: 12,
    fontWeight: '800',
  },
  onboardingScreen: {
    flex: 1,
    paddingHorizontal: 22,
    paddingBottom: 34,
    justifyContent: 'center',
  },
  onboardingHero: {
    padding: 24,
    borderRadius: 30,
    alignItems: 'center',
    backgroundColor: '#DDE9FF',
    borderWidth: 1.5,
    borderColor: '#DCE7FF',
    ...FLOATING_SHADOW,
  },
  onboardingIcon: {
    width: 72,
    height: 72,
    marginBottom: 16,
    borderRadius: 26,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.purpleDark,
  },
  onboardingTitle: {
    color: COLORS.ink,
    textAlign: 'center',
    fontSize: 29,
    lineHeight: 34,
    fontWeight: '900',
    letterSpacing: -0.8,
  },
  onboardingText: {
    marginTop: 9,
    color: COLORS.muted,
    textAlign: 'center',
    fontSize: 14,
    lineHeight: 21,
    fontWeight: '700',
  },
  onboardingSteps: {
    marginTop: 22,
    marginBottom: 20,
    paddingLeft: 4,
    gap: 16,
  },
  onboardingStep: {
    minHeight: 64,
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
  onboardingStepMarker: {
    width: 26,
    height: 26,
    marginTop: 4,
    borderRadius: 13,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.purpleDark,
  },
  onboardingStepNumber: {
    color: COLORS.white,
    fontSize: 11,
    fontWeight: '900',
  },
  onboardingStepIcon: {
    width: 42,
    height: 42,
    marginLeft: 11,
    marginRight: 12,
    borderRadius: 15,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.purplePale,
    borderWidth: 1,
    borderColor: '#E0D7FF',
  },
  onboardingStepCopy: {
    flex: 1,
    paddingTop: 1,
  },
  onboardingStepTitle: {
    color: COLORS.ink,
    fontSize: 15,
    fontWeight: '900',
  },
  onboardingStepText: {
    marginTop: 3,
    color: COLORS.muted,
    fontSize: 12,
    lineHeight: 18,
    fontWeight: '700',
  },
  onboardingReminderButton: {
    minHeight: 52,
    marginTop: 11,
    borderRadius: 17,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: COLORS.bluePale,
    borderWidth: 1.5,
    borderColor: '#DCE7FF',
  },
  onboardingReminderText: {
    color: COLORS.blue,
    fontSize: 13,
    fontWeight: '900',
  },
  listContent: {
    paddingHorizontal: 20,
    paddingBottom: 36,
  },
  singleScreenContent: {
    flexGrow: 1,
    paddingHorizontal: 20,
    paddingBottom: 42,
  },
  homeContent: {
    paddingHorizontal: 20,
    paddingBottom: 28,
  },
  homeHero: {
    minHeight: 365,
    marginTop: 8,
    borderRadius: 38,
    overflow: 'hidden',
    backgroundColor: '#DDE9FF',
    ...FLOATING_SHADOW,
  },
  heroCloudOne: {
    position: 'absolute',
    width: 215,
    height: 215,
    borderRadius: 108,
    left: -58,
    top: 36,
    backgroundColor: '#FFF0DC',
    opacity: 0.9,
  },
  heroCloudTwo: {
    position: 'absolute',
    width: 225,
    height: 225,
    borderRadius: 113,
    right: -76,
    top: -20,
    backgroundColor: '#E8FBF4',
    opacity: 0.8,
  },
  heroCloudThree: {
    position: 'absolute',
    width: 310,
    height: 180,
    borderRadius: 90,
    left: 10,
    bottom: -28,
    backgroundColor: '#FFF9F5',
    opacity: 0.92,
  },
  homeTopRow: {
    padding: 22,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  avatarBadge: {
    width: 54,
    height: 54,
    borderRadius: 27,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.white,
    borderWidth: 4,
    borderColor: 'rgba(255,255,255,0.65)',
  },
  avatarText: {
    color: COLORS.purpleDark,
    fontSize: 24,
    fontWeight: '900',
  },
  homeStatsPill: {
    paddingHorizontal: 11,
    height: 34,
    borderRadius: 17,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    backgroundColor: 'rgba(255,255,255,0.78)',
  },
  homeStatsPillText: {
    color: COLORS.ink,
    fontSize: 12,
    fontWeight: '900',
  },
  paperPlane: {
    position: 'absolute',
    top: 135,
    alignSelf: 'center',
    width: 52,
    height: 52,
    borderRadius: 26,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.48)',
    transform: [{ rotate: '-12deg' }],
  },
  heroGreeting: {
    position: 'absolute',
    left: 22,
    right: 22,
    bottom: 47,
    alignItems: 'center',
  },
  homeTitle: {
    color: '#111827',
    textAlign: 'center',
    fontSize: 30,
    lineHeight: 36,
    fontWeight: '900',
    letterSpacing: -1,
  },
  homeSubtitle: {
    marginTop: 7,
    color: COLORS.ink,
    textAlign: 'center',
    fontSize: 13,
    fontWeight: '700',
  },
  homeOverviewCard: {
    marginTop: -33,
    marginHorizontal: 17,
    padding: 18,
    borderRadius: 24,
    backgroundColor: COLORS.surface,
    borderWidth: 1.5,
    borderColor: COLORS.border,
    ...SOFT_SHADOW,
    zIndex: 2,
  },
  overviewHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  homeSectionTitle: {
    color: COLORS.ink,
    fontSize: 16,
    fontWeight: '900',
  },
  overviewProgressRing: {
    width: 43,
    height: 43,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: COLORS.teal,
    backgroundColor: COLORS.tealPale,
  },
  overviewProgressText: {
    color: COLORS.teal,
    fontSize: 12,
    fontWeight: '900',
  },
  homeIdeaGrid: {
    marginTop: 14,
    flexDirection: 'row',
    gap: 10,
  },
  homeMiniCard: {
    flex: 1,
    minHeight: 82,
    padding: 12,
    borderRadius: 16,
  },
  homeMiniIcon: {
    width: 27,
    height: 27,
    borderRadius: 9,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.62)',
  },
  homeMiniTitle: {
    marginTop: 9,
    color: COLORS.ink,
    fontSize: 13,
    fontWeight: '900',
  },
  homeMiniSubtitle: {
    marginTop: 3,
    color: COLORS.muted,
    fontSize: 10,
    fontWeight: '700',
  },
  homeDottedLine: {
    marginTop: 15,
    borderTopWidth: 1,
    borderStyle: 'dashed',
    borderColor: '#D7DEE8',
  },
  homePrimaryButton: {
    marginTop: 13,
    height: 50,
    borderRadius: 17,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.blue,
    ...FLOATING_SHADOW,
  },
  homePrimaryButtonText: {
    color: COLORS.white,
    fontSize: 15,
    fontWeight: '900',
  },
  homeSkillCard: {
    marginTop: 17,
    padding: 17,
    borderRadius: 22,
    borderWidth: 1.5,
    borderColor: COLORS.border,
    backgroundColor: COLORS.tealPale,
    ...SOFT_SHADOW,
  },
  homeSkillCopy: {
    paddingRight: 78,
  },
  homeSkillTitle: {
    color: COLORS.ink,
    fontSize: 17,
    fontWeight: '900',
  },
  homeSkillSubtitle: {
    marginTop: 4,
    color: COLORS.muted,
    fontSize: 12,
    fontWeight: '600',
  },
  homeSkillBadge: {
    marginTop: 7,
    fontSize: 11,
    fontWeight: '900',
  },
  homeSkillTrack: {
    height: 7,
    marginTop: 14,
    marginRight: 68,
    borderRadius: 4,
    overflow: 'hidden',
    backgroundColor: '#EDE8F7',
  },
  homeSkillFill: {
    height: '100%',
    borderRadius: 4,
    backgroundColor: COLORS.teal,
  },
  progressShine: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    width: '42%',
    borderRadius: 999,
    backgroundColor: 'rgba(255,255,255,0.86)',
  },
  progressShineComplete: {
    width: '68%',
    backgroundColor: 'rgba(255,255,255,0.96)',
  },
  homeStartButton: {
    position: 'absolute',
    right: 17,
    top: 28,
    height: 36,
    paddingHorizontal: 14,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1.5,
    borderColor: COLORS.blue,
    backgroundColor: COLORS.bluePale,
  },
  homeStartButtonText: {
    color: COLORS.blue,
    fontSize: 12,
    fontWeight: '900',
  },
  homeAchievementsCard: {
    marginTop: 17,
    padding: 15,
    borderRadius: 20,
    borderWidth: 1.5,
    borderColor: COLORS.border,
    backgroundColor: COLORS.surface,
    ...SOFT_SHADOW,
  },
  homeAchievementsHeader: {
    marginBottom: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  homeAchievementsCount: {
    color: COLORS.purpleDark,
    fontSize: 11,
    fontWeight: '900',
  },
  homeAchievementRow: {
    flexDirection: 'row',
    gap: 8,
  },
  homeAchievementChip: {
    flex: 1,
    minHeight: 42,
    paddingHorizontal: 8,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
  },
  homeAchievementText: {
    maxWidth: '100%',
    color: COLORS.muted,
    fontSize: 9,
    fontWeight: '900',
  },
  homePromptSection: {
    marginTop: 22,
  },
  nextActionRow: {
    marginTop: 13,
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 10,
  },
  homeActionButton: {
    flex: 1,
    minHeight: 72,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.surface,
    borderWidth: 1.5,
    borderColor: COLORS.border,
    ...SOFT_SHADOW,
  },
  homeActionLabel: {
    marginTop: 7,
    color: COLORS.muted,
    fontSize: 10,
    fontWeight: '800',
  },
  nextWordsCard: {
    marginTop: 17,
    padding: 17,
    borderRadius: 22,
    borderWidth: 1.5,
    borderColor: COLORS.border,
    backgroundColor: COLORS.surface,
    ...SOFT_SHADOW,
  },
  nextWordRow: {
    marginTop: 13,
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
  },
  nextWordIcon: {
    width: 42,
    height: 42,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.orangePale,
  },
  nextWordInitial: {
    color: COLORS.orange,
    fontSize: 18,
    fontWeight: '900',
  },
  nextWordCopy: {
    flex: 1,
    marginLeft: 4,
    minWidth: 0,
  },
  nextWordTerm: {
    flexShrink: 1,
    minWidth: 0,
    color: COLORS.ink,
    fontSize: 14,
    lineHeight: 18,
    fontWeight: '900',
  },
  nextWordDefinition: {
    marginTop: 2,
    color: COLORS.muted,
    fontSize: 11,
    fontWeight: '600',
  },
  nextWordMastery: {
    color: COLORS.blue,
    fontSize: 12,
    fontWeight: '900',
  },
  nextWordReason: {
    minWidth: 54,
    minHeight: 30,
    paddingHorizontal: 9,
    borderRadius: 11,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.orangePale,
    borderWidth: 1,
    borderColor: '#FFE0B7',
  },
  nextWordReasonText: {
    color: '#B56A14',
    fontSize: 10,
    fontWeight: '900',
  },
  homeReminderStrip: {
    marginTop: 15,
    padding: 14,
    borderRadius: 17,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 9,
    backgroundColor: COLORS.bluePale,
    borderWidth: 1,
    borderColor: '#DDE8FF',
  },
  homeReminderText: {
    flex: 1,
    color: '#5268C9',
    fontSize: 12,
    lineHeight: 17,
    fontWeight: '700',
  },
  header: {
    paddingTop: 8,
    paddingBottom: 18,
  },
  screenHeaderCard: {
    minHeight: 218,
    padding: 18,
    borderRadius: 34,
    overflow: 'hidden',
    backgroundColor: '#D9E3FF',
    ...FLOATING_SHADOW,
  },
  screenHeaderCloudOne: {
    position: 'absolute',
    top: -38,
    right: -52,
    width: 170,
    height: 170,
    borderRadius: 85,
    backgroundColor: '#FFE4EC',
    opacity: 0.8,
  },
  screenHeaderCloudTwo: {
    position: 'absolute',
    left: -58,
    bottom: 16,
    width: 190,
    height: 132,
    borderRadius: 66,
    backgroundColor: '#FFF3E8',
    opacity: 0.86,
  },
  screenHeaderCloudThree: {
    position: 'absolute',
    right: 18,
    bottom: -38,
    width: 220,
    height: 118,
    borderRadius: 59,
    backgroundColor: '#FFF9F7',
    opacity: 0.92,
  },
  screenHeaderPlane: {
    position: 'absolute',
    top: 84,
    right: 35,
    width: 46,
    height: 46,
    borderRadius: 23,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.48)',
    transform: [{ rotate: '-14deg' }],
  },
  brandRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 28,
  },
  miniLogo: {
    width: 30,
    height: 30,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.purple,
  },
  brandName: {
    marginLeft: 9,
    color: COLORS.purpleDark,
    fontSize: 15,
    fontWeight: '900',
    letterSpacing: 1.2,
  },
  eyebrow: {
    marginBottom: 7,
    color: COLORS.purpleDark,
    fontSize: 12,
    fontWeight: '900',
    letterSpacing: 1.4,
  },
  screenTitle: {
    color: COLORS.ink,
    fontSize: 29,
    lineHeight: 34,
    fontWeight: '900',
    letterSpacing: -1.2,
  },
  screenSubtitle: {
    marginTop: 7,
    color: COLORS.muted,
    fontSize: 15,
    lineHeight: 21,
    fontWeight: '500',
  },
  headerTextCard: {
    marginTop: 'auto',
    padding: 17,
    borderRadius: 24,
    backgroundColor: 'rgba(255,255,255,0.72)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.78)',
  },
  progressCard: {
    minHeight: 82,
    padding: 15,
    borderWidth: 1.5,
    borderColor: COLORS.border,
    borderRadius: 24,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.tealPale,
    ...SOFT_SHADOW,
  },
  progressIcon: {
    width: 48,
    height: 48,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.white,
  },
  progressCopy: {
    flex: 1,
    marginLeft: 13,
  },
  progressNumber: {
    color: COLORS.ink,
    fontSize: 18,
    fontWeight: '900',
  },
  progressLabel: {
    marginTop: 2,
    color: COLORS.purpleDark,
    fontSize: 12,
    fontWeight: '700',
  },
  studyButton: {
    paddingHorizontal: 12,
    height: 36,
    borderRadius: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: COLORS.purple,
    ...SOFT_SHADOW,
  },
  studyButtonText: {
    color: COLORS.white,
    fontSize: 11,
    fontWeight: '900',
    letterSpacing: 0.5,
  },
  addButton: {
    marginTop: 16,
    minHeight: 82,
    paddingHorizontal: 17,
    borderRadius: 24,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.teal,
    ...FLOATING_SHADOW,
  },
  addIcon: {
    width: 43,
    height: 43,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.2)',
  },
  addButtonCopy: {
    flex: 1,
    marginLeft: 13,
  },
  addButtonTitle: {
    color: COLORS.white,
    fontSize: 17,
    fontWeight: '900',
  },
  addButtonSubtitle: {
    marginTop: 3,
    color: '#EAF6FF',
    fontSize: 12,
    fontWeight: '600',
  },
  sampleWordsCard: {
    marginTop: 14,
    padding: 14,
    borderRadius: 20,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 11,
    backgroundColor: COLORS.purplePale,
    borderWidth: 1.5,
    borderColor: '#E0D7FF',
  },
  sampleWordsIcon: {
    width: 40,
    height: 40,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.white,
  },
  sampleWordsCopy: {
    flex: 1,
  },
  sampleWordsTitle: {
    color: COLORS.ink,
    fontSize: 13,
    fontWeight: '900',
  },
  sampleWordsText: {
    marginTop: 3,
    color: '#655B95',
    fontSize: 11,
    lineHeight: 16,
    fontWeight: '700',
  },
  sampleWordsButton: {
    minHeight: 34,
    paddingHorizontal: 12,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.white,
    borderWidth: 1,
    borderColor: '#D8CEFF',
  },
  sampleWordsButtonText: {
    color: COLORS.purpleDark,
    fontSize: 11,
    fontWeight: '900',
  },
  listToolbar: {
    marginTop: 27,
    marginBottom: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  sectionTitle: {
    color: COLORS.muted,
    fontSize: 12,
    fontWeight: '900',
    letterSpacing: 1.2,
  },
  segmentedControl: {
    padding: 3,
    borderRadius: 11,
    flexDirection: 'row',
    backgroundColor: 'rgba(255,255,255,0.66)',
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  wordSearchBox: {
    minHeight: 48,
    marginBottom: 13,
    paddingHorizontal: 14,
    borderWidth: 1.5,
    borderColor: COLORS.border,
    borderRadius: 17,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 9,
    backgroundColor: 'rgba(255,251,255,0.86)',
    ...SOFT_SHADOW,
  },
  wordSearchInput: {
    flex: 1,
    minWidth: 0,
    color: COLORS.ink,
    fontSize: 14,
    fontWeight: '800',
  },
  wordSearchClear: {
    width: 25,
    height: 25,
    borderRadius: 9,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.bluePale,
  },
  sortButton: {
    width: 35,
    height: 29,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  sortButtonActive: {
    backgroundColor: COLORS.surface,
    ...SOFT_SHADOW,
  },
  wordRow: {
    minHeight: 82,
    marginBottom: 10,
    padding: 13,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.9)',
    borderRadius: 22,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.white,
    ...SOFT_SHADOW,
  },
  pressed: {
    opacity: 0.75,
    transform: [{ scale: 0.99 }],
  },
  letterBadge: {
    width: 48,
    height: 48,
    borderRadius: 15,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.72)',
  },
  letterText: {
    fontSize: 22,
    fontWeight: '900',
  },
  wordRowCopy: {
    flex: 1,
    marginHorizontal: 13,
    minWidth: 0,
  },
  wordTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 7,
  },
  wordTitleRowWrapped: {
    alignItems: 'flex-start',
  },
  wordTerm: {
    flexShrink: 1,
    minWidth: 0,
    color: COLORS.ink,
    fontSize: 17,
    lineHeight: 21,
    fontWeight: '900',
  },
  wordTermLong: {
    width: '100%',
  },
  speakButton: {
    width: 30,
    height: 30,
    borderWidth: 1,
    borderColor: '#DCE7FF',
    borderRadius: 11,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.bluePale,
  },
  speakButtonLarge: {
    width: 42,
    height: 42,
    borderRadius: 15,
    backgroundColor: COLORS.white,
    ...SOFT_SHADOW,
  },
  partOfSpeechPill: {
    maxWidth: 92,
    paddingHorizontal: 7,
    paddingVertical: 3,
    borderRadius: 8,
    overflow: 'hidden',
    color: COLORS.purpleDark,
    backgroundColor: COLORS.purplePale,
    fontSize: 9,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  wordDefinition: {
    marginTop: 3,
    color: COLORS.muted,
    fontSize: 12,
    lineHeight: 17,
    fontWeight: '500',
  },
  commonWordsLine: {
    marginTop: 4,
    color: COLORS.purpleDark,
    fontSize: 11,
    fontWeight: '800',
  },
  wordMeta: {
    marginTop: 3,
    color: COLORS.blue,
    fontSize: 11,
    fontWeight: '700',
  },
  reviewCount: {
    minWidth: 31,
    height: 26,
    paddingHorizontal: 7,
    borderRadius: 9,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 3,
    backgroundColor: COLORS.bluePale,
  },
  reviewText: {
    color: COLORS.muted,
    fontSize: 11,
    fontWeight: '800',
  },
  emptyState: {
    paddingVertical: 32,
    alignItems: 'center',
  },
  emptyIcon: {
    width: 76,
    height: 76,
    marginBottom: 16,
    borderRadius: 26,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.purplePale,
  },
  emptyTitle: {
    color: COLORS.ink,
    fontSize: 18,
    fontWeight: '900',
  },
  emptyText: {
    maxWidth: 270,
    marginTop: 6,
    color: COLORS.muted,
    textAlign: 'center',
    fontSize: 14,
    lineHeight: 20,
  },
  cardScreenContent: {
    paddingHorizontal: 20,
    paddingBottom: 34,
  },
  cardProgressRow: {
    marginBottom: 17,
  },
  cardProgressText: {
    marginBottom: 8,
    color: COLORS.muted,
    fontSize: 11,
    fontWeight: '900',
    letterSpacing: 0.8,
  },
  progressTrack: {
    height: 9,
    borderRadius: 5,
    overflow: 'hidden',
    backgroundColor: '#EDE8F7',
  },
  progressFill: {
    height: '100%',
    borderRadius: 5,
    backgroundColor: COLORS.teal,
  },
  flashcard: {
    minHeight: 390,
    padding: 22,
    borderWidth: 1.5,
    borderColor: COLORS.border,
    borderRadius: 31,
    backgroundColor: '#FFFBF3',
    ...FLOATING_SHADOW,
  },
  flashcardRevealed: {
    borderColor: '#FFE0B7',
    backgroundColor: '#FFF7EA',
  },
  flashcardPressed: {
    transform: [{ scale: 0.99 }],
  },
  cardTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  cardLabel: {
    paddingHorizontal: 11,
    paddingVertical: 7,
    borderRadius: 9,
    backgroundColor: COLORS.bluePale,
  },
  cardLabelRevealed: {
    backgroundColor: COLORS.yellowPale,
  },
  cardLabelText: {
    color: COLORS.blue,
    fontSize: 10,
    fontWeight: '900',
    letterSpacing: 1,
  },
  cardLabelTextRevealed: {
    color: '#C59600',
  },
  flashcardBody: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  flashcardWordRow: {
    maxWidth: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    flexWrap: 'wrap',
    gap: 10,
  },
  flashcardWord: {
    maxWidth: '100%',
    flexShrink: 1,
    color: COLORS.ink,
    textAlign: 'center',
    fontSize: 38,
    lineHeight: 45,
    fontWeight: '900',
    letterSpacing: -1.3,
  },
  flashcardWordLong: {
    width: '100%',
    fontSize: 34,
    lineHeight: 40,
  },
  flashcardMetaRow: {
    marginTop: 13,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    flexWrap: 'wrap',
    gap: 8,
  },
  flashcardMetaPill: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 10,
    overflow: 'hidden',
    color: COLORS.purpleDark,
    backgroundColor: COLORS.purplePale,
    fontSize: 10,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  flashcardPronunciation: {
    color: COLORS.blue,
    fontSize: 13,
    fontWeight: '800',
  },
  flashcardDefinition: {
    maxWidth: 300,
    marginTop: 20,
    color: COLORS.ink,
    textAlign: 'center',
    fontSize: 18,
    lineHeight: 26,
    fontWeight: '600',
  },
  fullDefinitionText: {
    maxWidth: 310,
    marginTop: 10,
    color: COLORS.muted,
    textAlign: 'center',
    fontSize: 12,
    lineHeight: 17,
    fontWeight: '600',
  },
  cardNavigationRow: {
    marginTop: 16,
    flexDirection: 'row',
    gap: 12,
  },
  cardNavigationButton: {
    flex: 1,
    height: 52,
    borderRadius: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 7,
    borderBottomWidth: 4,
  },
  cardNavigationButtonSecondary: {
    borderWidth: 1.5,
    borderColor: COLORS.border,
    borderBottomColor: '#D8D0EC',
    backgroundColor: 'rgba(255,255,255,0.72)',
  },
  cardNavigationButtonPrimary: {
    borderBottomColor: COLORS.purpleDark,
    backgroundColor: COLORS.purple,
    ...SOFT_SHADOW,
  },
  cardNavigationButtonTextSecondary: {
    color: COLORS.purpleDark,
    fontSize: 14,
    fontWeight: '900',
  },
  cardNavigationButtonTextPrimary: {
    color: COLORS.white,
    fontSize: 14,
    fontWeight: '900',
  },
  wordInfoPanel: {
    width: '100%',
    marginTop: 18,
    padding: 14,
    borderRadius: 16,
    backgroundColor: '#F0FAFF',
    borderWidth: 1,
    borderColor: '#DCE7FF',
  },
  infoChipRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 7,
  },
  infoChip: {
    paddingHorizontal: 9,
    paddingVertical: 6,
    borderRadius: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    backgroundColor: COLORS.white,
  },
  infoChipText: {
    color: COLORS.purpleDark,
    fontSize: 11,
    fontWeight: '900',
  },
  wordInfoText: {
    marginTop: 10,
    color: '#5268C9',
    fontSize: 12,
    lineHeight: 17,
    fontWeight: '700',
  },
  commonWordsBox: {
    marginTop: 12,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: '#DCE7FF',
  },
  commonWordsTitle: {
    marginBottom: 8,
    color: COLORS.blue,
    fontSize: 9,
    fontWeight: '900',
    letterSpacing: 0.8,
  },
  commonWordsWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 7,
  },
  commonWordChip: {
    paddingHorizontal: 9,
    paddingVertical: 6,
    borderRadius: 10,
    overflow: 'hidden',
    color: COLORS.purpleDark,
    backgroundColor: COLORS.white,
    fontSize: 11,
    fontWeight: '900',
  },
  originBox: {
    marginTop: 11,
    paddingTop: 11,
    borderTopWidth: 1,
    borderTopColor: '#DCE7FF',
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
  },
  originCopy: {
    flex: 1,
  },
  originLabel: {
    marginBottom: 3,
    color: COLORS.blue,
    fontSize: 9,
    fontWeight: '900',
    letterSpacing: 0.8,
  },
  originText: {
    marginBottom: 8,
    color: '#5268C9',
    fontSize: 12,
    lineHeight: 17,
    fontWeight: '600',
  },
  historyExternalLink: {
    alignSelf: 'flex-start',
    minHeight: 34,
    marginTop: 4,
    paddingHorizontal: 10,
    borderRadius: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: COLORS.white,
    borderWidth: 1,
    borderColor: '#DCE7FF',
  },
  historyExternalLinkText: {
    color: COLORS.blue,
    fontSize: 11,
    fontWeight: '900',
  },
  tapHint: {
    marginTop: 27,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  tapHintText: {
    color: COLORS.muted,
    fontSize: 13,
    fontWeight: '600',
  },
  exampleBox: {
    width: '100%',
    marginTop: 25,
    padding: 16,
    borderRadius: 16,
    flexDirection: 'row',
    gap: 10,
    backgroundColor: COLORS.orangePale,
  },
  exampleText: {
    flex: 1,
    color: '#9A5F18',
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '600',
    fontStyle: 'italic',
  },
  cardActions: {
    marginTop: 18,
    flexDirection: 'row',
    gap: 12,
  },
  answerButton: {
    flex: 1,
    height: 55,
    borderRadius: 17,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    borderBottomWidth: 4,
  },
  againButton: {
    borderWidth: 2,
    borderColor: '#FFD7D7',
    borderBottomWidth: 4,
    backgroundColor: COLORS.redPale,
    ...SOFT_SHADOW,
  },
  gotItButton: {
    borderBottomColor: COLORS.purpleDark,
    backgroundColor: COLORS.purple,
    ...SOFT_SHADOW,
  },
  answerButtonText: {
    fontSize: 13,
    fontWeight: '900',
    letterSpacing: 0.7,
  },
  cardTip: {
    marginTop: 19,
    color: COLORS.muted,
    textAlign: 'center',
    fontSize: 13,
    fontWeight: '600',
  },
  quizContent: {
    paddingHorizontal: 20,
    paddingBottom: 32,
  },
  quizIntroCard: {
    padding: 23,
    borderWidth: 1.5,
    borderColor: COLORS.border,
    borderRadius: 30,
    alignItems: 'center',
    backgroundColor: '#FFF8EC',
    ...FLOATING_SHADOW,
  },
  quizIllustration: {
    width: 118,
    height: 118,
    marginBottom: 17,
    borderRadius: 40,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FFF1D6',
  },
  sparkleOne: {
    position: 'absolute',
    top: 12,
    right: 12,
  },
  sparkleTwo: {
    position: 'absolute',
    bottom: 17,
    left: 15,
  },
  quizIntroTitle: {
    color: COLORS.ink,
    textAlign: 'center',
    fontSize: 22,
    fontWeight: '900',
    letterSpacing: -0.5,
  },
  quizIntroText: {
    marginTop: 9,
    color: COLORS.muted,
    textAlign: 'center',
    fontSize: 14,
    lineHeight: 21,
  },
  quizFacts: {
    width: '100%',
    marginVertical: 22,
    padding: 14,
    borderRadius: 16,
    flexDirection: 'row',
    justifyContent: 'space-around',
    backgroundColor: COLORS.bluePale,
    borderWidth: 1,
    borderColor: '#DCE7FF',
  },
  quizFact: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  quizFactText: {
    color: '#5268C9',
    fontSize: 12,
    fontWeight: '800',
  },
  primaryButton: {
    width: '100%',
    minHeight: 56,
    paddingHorizontal: 21,
    borderRadius: 17,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 9,
    backgroundColor: COLORS.blue,
    ...FLOATING_SHADOW,
  },
  primaryButtonPressed: {
    transform: [{ translateY: 3 }],
    borderBottomWidth: 2,
  },
  primaryButtonDisabled: {
    backgroundColor: '#CFC8DF',
    boxShadow: 'none',
    elevation: 0,
  },
  primaryButtonText: {
    color: COLORS.white,
    fontSize: 14,
    fontWeight: '900',
    letterSpacing: 0.7,
  },
  quizProgressTrack: {
    height: 10,
    marginBottom: 20,
    borderRadius: 6,
    overflow: 'hidden',
    backgroundColor: '#EDE8F7',
  },
  quizProgressFill: {
    height: '100%',
    borderRadius: 6,
    backgroundColor: COLORS.orange,
  },
  questionCard: {
    minHeight: 150,
    marginBottom: 18,
    padding: 20,
    borderWidth: 1.5,
    borderColor: '#FFE0B7',
    borderRadius: 26,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.orangePale,
    ...SOFT_SHADOW,
  },
  questionPrompt: {
    color: COLORS.orange,
    fontSize: 11,
    fontWeight: '900',
    letterSpacing: 1,
  },
  questionWord: {
    maxWidth: '100%',
    marginTop: 12,
    color: COLORS.ink,
    textAlign: 'center',
    fontSize: 34,
    lineHeight: 40,
    fontWeight: '900',
    letterSpacing: -1,
  },
  optionsList: {
    gap: 10,
  },
  optionButton: {
    minHeight: 66,
    padding: 11,
    borderWidth: 1.5,
    borderColor: COLORS.border,
    borderRadius: 20,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.surface,
    ...SOFT_SHADOW,
  },
  optionCorrect: {
    borderColor: COLORS.green,
    backgroundColor: COLORS.greenPale,
  },
  optionWrong: {
    borderColor: COLORS.red,
    backgroundColor: COLORS.redPale,
  },
  optionLetter: {
    width: 38,
    height: 38,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.bluePale,
  },
  optionLetterCorrect: {
    backgroundColor: COLORS.green,
  },
  optionLetterWrong: {
    backgroundColor: COLORS.red,
  },
  optionLetterText: {
    color: COLORS.muted,
    fontSize: 13,
    fontWeight: '900',
  },
  optionText: {
    flex: 1,
    marginLeft: 12,
    color: COLORS.ink,
    fontSize: 14,
    lineHeight: 19,
    fontWeight: '600',
  },
  feedbackBox: {
    marginVertical: 15,
    padding: 14,
    borderRadius: 15,
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
  },
  feedbackCorrect: {
    backgroundColor: COLORS.greenPale,
  },
  feedbackWrong: {
    backgroundColor: COLORS.redPale,
  },
  feedbackCopy: {
    flex: 1,
  },
  feedbackTitle: {
    color: COLORS.ink,
    fontSize: 14,
    fontWeight: '900',
  },
  feedbackText: {
    marginTop: 2,
    color: COLORS.muted,
    fontSize: 12,
    lineHeight: 17,
    fontWeight: '600',
  },
  completeCard: {
    marginTop: 12,
    padding: 27,
    borderWidth: 1.5,
    borderColor: COLORS.border,
    borderRadius: 31,
    alignItems: 'center',
    backgroundColor: COLORS.surface,
    ...FLOATING_SHADOW,
  },
  completeBadge: {
    width: 82,
    height: 82,
    marginBottom: 18,
    borderRadius: 28,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.teal,
    ...SOFT_SHADOW,
  },
  completeTitle: {
    color: COLORS.ink,
    fontSize: 23,
    fontWeight: '900',
  },
  completeScore: {
    marginTop: 13,
    color: COLORS.teal,
    fontSize: 43,
    fontWeight: '900',
  },
  completeTotal: {
    color: COLORS.muted,
    fontSize: 24,
  },
  completeText: {
    maxWidth: 290,
    marginTop: 9,
    color: COLORS.muted,
    textAlign: 'center',
    fontSize: 14,
    lineHeight: 21,
  },
  comeBackPill: {
    marginTop: 23,
    paddingHorizontal: 14,
    paddingVertical: 11,
    borderRadius: 13,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
    backgroundColor: COLORS.yellowPale,
  },
  comeBackText: {
    color: '#9A7800',
    fontSize: 12,
    fontWeight: '800',
  },
  emptyPractice: {
    marginTop: 20,
    padding: 28,
    borderWidth: 1.5,
    borderColor: COLORS.border,
    borderRadius: 30,
    alignItems: 'center',
    backgroundColor: COLORS.surface,
    ...SOFT_SHADOW,
  },
  emptyPracticeIcon: {
    width: 92,
    height: 92,
    marginBottom: 18,
    borderRadius: 32,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.bluePale,
  },
  emptyPracticeTitle: {
    color: COLORS.ink,
    fontSize: 20,
    fontWeight: '900',
  },
  emptyPracticeText: {
    marginTop: 7,
    color: COLORS.muted,
    textAlign: 'center',
    fontSize: 14,
    lineHeight: 20,
  },
  dashboardContent: {
    paddingHorizontal: 20,
    paddingBottom: 34,
  },
  dashboardHero: {
    minHeight: 176,
    padding: 21,
    borderRadius: 31,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.blue,
    ...FLOATING_SHADOW,
  },
  heroCopy: {
    flex: 1,
    paddingRight: 14,
  },
  heroLabel: {
    color: '#E9E4FF',
    fontSize: 10,
    fontWeight: '900',
    letterSpacing: 1.1,
  },
  heroValue: {
    marginTop: 5,
    color: COLORS.white,
    fontSize: 43,
    lineHeight: 49,
    fontWeight: '900',
    letterSpacing: -1.5,
  },
  heroLevelTitle: {
    marginTop: 8,
    color: COLORS.white,
    fontSize: 19,
    lineHeight: 24,
    fontWeight: '900',
  },
  heroText: {
    marginTop: 5,
    color: '#F1EEFF',
    fontSize: 12,
    lineHeight: 17,
    fontWeight: '600',
  },
  heroLevelTrack: {
    height: 8,
    marginTop: 11,
    borderRadius: 4,
    overflow: 'hidden',
    backgroundColor: 'rgba(255,255,255,0.28)',
  },
  heroLevelFill: {
    height: '100%',
    borderRadius: 4,
  },
  heroLevelNext: {
    marginTop: 6,
    color: '#F1EEFF',
    fontSize: 10,
    lineHeight: 13,
    fontWeight: '800',
  },
  masteryGauge: {
    width: 106,
    height: 106,
    padding: 8,
    borderRadius: 53,
    backgroundColor: 'rgba(255,255,255,0.32)',
  },
  masteryGaugeInner: {
    flex: 1,
    borderRadius: 45,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.white,
  },
  masteryGaugeCount: {
    marginTop: 2,
    color: COLORS.ink,
    fontSize: 16,
    fontWeight: '900',
  },
  masteryGaugeLabel: {
    color: COLORS.muted,
    fontSize: 8,
    fontWeight: '900',
    letterSpacing: 0.7,
  },
  statGrid: {
    marginTop: 15,
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    rowGap: 10,
  },
  dashboardStat: {
    width: '48.5%',
    minHeight: 91,
    padding: 13,
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 22,
    backgroundColor: COLORS.surface,
    ...SOFT_SHADOW,
  },
  dashboardStatIcon: {
    width: 34,
    height: 34,
    borderRadius: 11,
    alignItems: 'center',
    justifyContent: 'center',
  },
  dashboardStatValue: {
    position: 'absolute',
    top: 14,
    right: 14,
    color: COLORS.ink,
    fontSize: 22,
    fontWeight: '900',
    letterSpacing: -0.5,
  },
  dashboardStatLabel: {
    marginTop: 8,
    color: COLORS.muted,
    fontSize: 11,
    fontWeight: '800',
  },
  streakReminderGrid: {
    marginTop: 15,
    gap: 12,
  },
  streakCard: {
    padding: 17,
    borderWidth: 1.5,
    borderColor: '#FFE8C4',
    borderRadius: 26,
    backgroundColor: COLORS.orangePale,
    ...SOFT_SHADOW,
  },
  streakCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  streakFlame: {
    width: 46,
    height: 46,
    borderRadius: 15,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.yellow,
    ...SOFT_SHADOW,
  },
  streakHeaderCopy: {
    flex: 1,
    marginLeft: 12,
  },
  streakLabel: {
    color: '#9A7800',
    fontSize: 10,
    fontWeight: '900',
    letterSpacing: 0.8,
  },
  streakTitle: {
    marginTop: 2,
    color: COLORS.ink,
    fontSize: 20,
    fontWeight: '900',
    letterSpacing: -0.4,
  },
  longestStreak: {
    paddingHorizontal: 10,
    paddingVertical: 7,
    borderRadius: 10,
    overflow: 'hidden',
    color: '#9A7800',
    backgroundColor: COLORS.white,
    fontSize: 11,
    fontWeight: '900',
  },
  streakMessage: {
    marginTop: 13,
    color: '#9A7800',
    fontSize: 13,
    lineHeight: 18,
    fontWeight: '700',
  },
  streakWeek: {
    marginTop: 15,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  streakDay: {
    alignItems: 'center',
  },
  streakDayCircle: {
    width: 34,
    height: 34,
    borderRadius: 13,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.white,
  },
  streakDayCircleActive: {
    backgroundColor: COLORS.yellow,
  },
  streakDayCircleToday: {
    borderWidth: 2,
    borderColor: COLORS.green,
  },
  streakDayLabel: {
    marginTop: 6,
    color: '#9A7800',
    fontSize: 10,
    fontWeight: '800',
  },
  streakDayToday: {
    color: COLORS.purpleDark,
  },
  reminderCard: {
    padding: 17,
    borderWidth: 1.5,
    borderColor: COLORS.border,
    borderRadius: 26,
    backgroundColor: COLORS.bluePale,
    ...SOFT_SHADOW,
  },
  reminderHeader: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  reminderIcon: {
    width: 44,
    height: 44,
    borderRadius: 15,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.bluePale,
  },
  reminderHeaderCopy: {
    flex: 1,
    marginLeft: 12,
  },
  reminderLabel: {
    color: COLORS.blue,
    fontSize: 10,
    fontWeight: '900',
    letterSpacing: 0.8,
  },
  reminderTitle: {
    marginTop: 2,
    color: COLORS.ink,
    fontSize: 19,
    fontWeight: '900',
  },
  reminderSwitch: {
    width: 50,
    height: 30,
    padding: 4,
    borderRadius: 15,
    justifyContent: 'center',
    backgroundColor: '#E3DEEE',
  },
  reminderSwitchOn: {
    backgroundColor: COLORS.teal,
  },
  reminderSwitchKnob: {
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: COLORS.white,
  },
  reminderSwitchKnobOn: {
    alignSelf: 'flex-end',
  },
  reminderText: {
    marginTop: 12,
    color: COLORS.muted,
    fontSize: 12,
    lineHeight: 17,
    fontWeight: '600',
  },
  reminderCustomTime: {
    marginTop: 14,
    padding: 12,
    borderWidth: 1,
    borderColor: '#DCE7FF',
    borderRadius: 18,
    backgroundColor: 'rgba(255,255,255,0.62)',
  },
  reminderCustomHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  reminderCustomLabel: {
    color: COLORS.blue,
    fontSize: 10,
    fontWeight: '900',
    letterSpacing: 0.7,
  },
  reminderCustomValue: {
    color: COLORS.ink,
    fontSize: 13,
    fontWeight: '900',
  },
  reminderStepperRow: {
    marginTop: 10,
    flexDirection: 'row',
    gap: 10,
  },
  reminderTimeUnit: {
    flex: 1,
    padding: 10,
    borderWidth: 1,
    borderColor: '#DCE7FF',
    borderRadius: 15,
    backgroundColor: COLORS.white,
  },
  reminderTimeUnitLabel: {
    color: COLORS.muted,
    fontSize: 10,
    fontWeight: '900',
    letterSpacing: 0.5,
    textTransform: 'uppercase',
  },
  reminderStepperControls: {
    marginTop: 8,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  reminderStepperButton: {
    width: 32,
    height: 32,
    borderRadius: 11,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.bluePale,
  },
  reminderStepperValue: {
    flex: 1,
    color: COLORS.ink,
    fontSize: 16,
    fontWeight: '900',
    textAlign: 'center',
  },
  reminderQuickLabel: {
    marginTop: 14,
    color: COLORS.muted,
    fontSize: 10,
    fontWeight: '900',
    letterSpacing: 0.7,
  },
  reminderTimes: {
    marginTop: 8,
    flexDirection: 'row',
    gap: 8,
  },
  reminderTimeButton: {
    flex: 1,
    height: 38,
    borderWidth: 1.5,
    borderColor: COLORS.border,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.7)',
  },
  reminderTimeButtonActive: {
    borderColor: COLORS.blue,
    backgroundColor: COLORS.white,
  },
  reminderTimeText: {
    color: COLORS.muted,
    fontSize: 12,
    fontWeight: '900',
  },
  reminderTimeTextActive: {
    color: COLORS.blue,
  },
  dashboardSection: {
    marginTop: 15,
    padding: 18,
    borderWidth: 1.5,
    borderColor: COLORS.border,
    borderRadius: 25,
    backgroundColor: COLORS.surface,
    ...SOFT_SHADOW,
  },
  dashboardSectionHeader: {
    marginBottom: 17,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  dashboardSectionTitle: {
    color: COLORS.ink,
    fontSize: 12,
    fontWeight: '900',
    letterSpacing: 0.9,
  },
  dashboardBadge: {
    paddingHorizontal: 9,
    paddingVertical: 5,
    borderRadius: 9,
    backgroundColor: COLORS.bluePale,
  },
  dashboardBadgeText: {
    color: COLORS.blue,
    fontSize: 9,
    fontWeight: '900',
  },
  barChart: {
    height: 145,
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'space-between',
  },
  barColumn: {
    width: '11%',
    height: '100%',
    alignItems: 'center',
    justifyContent: 'flex-end',
  },
  barValue: {
    height: 17,
    color: COLORS.muted,
    fontSize: 9,
    fontWeight: '800',
  },
  barTrack: {
    width: 22,
    height: 101,
    borderRadius: 8,
    overflow: 'hidden',
    justifyContent: 'flex-end',
    backgroundColor: '#EFEAF8',
  },
  barFill: {
    width: '100%',
    minHeight: 4,
    borderRadius: 8,
  },
  barLabel: {
    marginTop: 7,
    color: COLORS.muted,
    fontSize: 10,
    fontWeight: '800',
  },
  barLabelToday: {
    color: COLORS.purpleDark,
  },
  chartLegendRow: {
    marginTop: 13,
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 18,
  },
  chartLegendItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
  },
  legendDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
  },
  chartLegendText: {
    color: COLORS.muted,
    fontSize: 9,
    fontWeight: '700',
  },
  dashboardSplit: {
    marginTop: 15,
    flexDirection: 'row',
    gap: 10,
  },
  accuracyCard: {
    flex: 1,
    minHeight: 218,
    padding: 15,
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 24,
    alignItems: 'center',
    backgroundColor: COLORS.purplePale,
    ...SOFT_SHADOW,
  },
  distributionCard: {
    flex: 1,
    minHeight: 218,
    padding: 15,
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 24,
    backgroundColor: COLORS.tealPale,
    ...SOFT_SHADOW,
  },
  dashboardCardLabel: {
    alignSelf: 'flex-start',
    color: COLORS.muted,
    fontSize: 10,
    fontWeight: '900',
    letterSpacing: 0.7,
  },
  accuracyGauge: {
    width: 112,
    height: 112,
    marginTop: 17,
    padding: 9,
    borderWidth: 7,
    borderColor: COLORS.purple,
    borderRadius: 56,
    backgroundColor: COLORS.purplePale,
  },
  accuracyGaugeInner: {
    flex: 1,
    borderRadius: 45,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.white,
  },
  accuracyValue: {
    color: COLORS.ink,
    fontSize: 25,
    fontWeight: '900',
    letterSpacing: -0.8,
  },
  accuracyLabel: {
    color: COLORS.purpleDark,
    fontSize: 8,
    fontWeight: '900',
    letterSpacing: 0.7,
  },
  accuracyDetail: {
    marginTop: 12,
    color: COLORS.muted,
    fontSize: 10,
    fontWeight: '700',
  },
  levelStack: {
    marginTop: 23,
    gap: 14,
  },
  levelRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  levelDot: {
    width: 9,
    height: 9,
    borderRadius: 5,
  },
  levelLabel: {
    flex: 1,
    marginLeft: 7,
    color: COLORS.muted,
    fontSize: 11,
    fontWeight: '700',
  },
  levelValue: {
    color: COLORS.ink,
    fontSize: 13,
    fontWeight: '900',
  },
  distributionBar: {
    height: 12,
    marginTop: 22,
    borderRadius: 6,
    overflow: 'hidden',
    flexDirection: 'row',
    backgroundColor: '#EFEAF8',
  },
  achievementGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  achievementCard: {
    width: '48%',
    minHeight: 146,
    padding: 12,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.72)',
    borderRadius: 18,
  },
  achievementHeader: {
    marginBottom: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  achievementIcon: {
    width: 34,
    height: 34,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  achievementStatus: {
    fontSize: 9,
    fontWeight: '900',
  },
  achievementTitle: {
    color: COLORS.ink,
    fontSize: 13,
    lineHeight: 17,
    fontWeight: '900',
  },
  achievementText: {
    flex: 1,
    marginTop: 4,
    color: COLORS.muted,
    fontSize: 10,
    lineHeight: 14,
    fontWeight: '700',
  },
  achievementTrack: {
    height: 7,
    marginTop: 10,
    borderRadius: 4,
    overflow: 'hidden',
    backgroundColor: 'rgba(255,255,255,0.78)',
  },
  achievementFill: {
    height: '100%',
    borderRadius: 4,
  },
  masteryRow: {
    marginBottom: 15,
  },
  masteryRowTop: {
    marginBottom: 7,
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
  },
  masteryWord: {
    flexShrink: 1,
    minWidth: 0,
    color: COLORS.ink,
    fontSize: 13,
    lineHeight: 17,
    fontWeight: '800',
  },
  masteryWordCopy: {
    flex: 1,
    minWidth: 0,
    paddingRight: 8,
  },
  masteryWordLevel: {
    marginTop: 2,
    fontSize: 9,
    fontWeight: '900',
  },
  masteryPercent: {
    fontSize: 11,
    fontWeight: '900',
  },
  masteryTrack: {
    height: 9,
    borderRadius: 5,
    overflow: 'hidden',
    backgroundColor: '#EFEAF8',
  },
  masteryFill: {
    height: '100%',
    borderRadius: 5,
  },
  trendRow: {
    marginBottom: 13,
    flexDirection: 'row',
    alignItems: 'center',
  },
  trendDate: {
    width: 48,
    color: COLORS.muted,
    fontSize: 10,
    fontWeight: '800',
  },
  trendTrack: {
    flex: 1,
    height: 11,
    borderRadius: 6,
    overflow: 'hidden',
    backgroundColor: '#EFEAF8',
  },
  trendFill: {
    height: '100%',
    borderRadius: 6,
  },
  trendScore: {
    width: 40,
    color: COLORS.ink,
    textAlign: 'right',
    fontSize: 11,
    fontWeight: '900',
  },
  dashboardEmptyText: {
    paddingVertical: 13,
    color: COLORS.muted,
    textAlign: 'center',
    fontSize: 12,
    lineHeight: 18,
    fontWeight: '600',
  },
  insightCard: {
    marginTop: 15,
    padding: 17,
    borderWidth: 1.5,
    borderColor: '#E3DAFF',
    borderRadius: 24,
    flexDirection: 'row',
    alignItems: 'flex-start',
    backgroundColor: COLORS.orangePale,
    ...SOFT_SHADOW,
  },
  insightIcon: {
    width: 43,
    height: 43,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.white,
  },
  insightCopy: {
    flex: 1,
    marginLeft: 12,
  },
  insightLabel: {
    color: COLORS.purple,
    fontSize: 9,
    fontWeight: '900',
    letterSpacing: 0.8,
  },
  insightTitle: {
    marginTop: 3,
    color: COLORS.ink,
    fontSize: 15,
    fontWeight: '900',
  },
  insightText: {
    marginTop: 4,
    color: '#6E619C',
    fontSize: 11,
    lineHeight: 16,
    fontWeight: '600',
  },
  legalCard: {
    marginTop: 15,
    padding: 16,
    borderWidth: 1.5,
    borderColor: '#DCE7FF',
    borderRadius: 24,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.bluePale,
    ...SOFT_SHADOW,
  },
  legalHeaderIcon: {
    width: 44,
    height: 44,
    borderRadius: 15,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.white,
  },
  legalCardCopy: {
    flex: 1,
    marginLeft: 12,
  },
  legalCardTitle: {
    color: COLORS.ink,
    fontSize: 15,
    fontWeight: '900',
  },
  legalCardText: {
    marginTop: 3,
    color: '#5268C9',
    fontSize: 11,
    lineHeight: 16,
    fontWeight: '600',
  },
  legalLinkStack: {
    gap: 7,
  },
  legalLink: {
    minWidth: 78,
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: COLORS.white,
  },
  legalLinkText: {
    color: COLORS.blue,
    fontSize: 11,
    fontWeight: '900',
  },
  estimateNote: {
    marginTop: 14,
    paddingHorizontal: 9,
    color: COLORS.muted,
    textAlign: 'center',
    fontSize: 10,
    lineHeight: 15,
    fontWeight: '500',
  },
  bottomTabs: {
    marginHorizontal: 20,
    marginBottom: 6,
    paddingTop: 7,
    paddingHorizontal: 10,
    borderWidth: 1,
    borderColor: 'rgba(232,226,245,0.86)',
    borderRadius: 24,
    flexDirection: 'row',
    backgroundColor: 'rgba(255,251,255,0.94)',
    boxShadow: '0 14px 35px rgba(90, 84, 145, 0.16)',
  },
  tabButton: {
    flex: 1,
    alignItems: 'center',
  },
  tabIcon: {
    width: 38,
    height: 30,
    borderRadius: 13,
    alignItems: 'center',
    justifyContent: 'center',
  },
  tabIconActive: {
    backgroundColor: COLORS.tealPale,
  },
  tabLabel: {
    marginTop: 1,
    color: COLORS.muted,
    fontSize: 10,
    fontWeight: '800',
  },
  tabLabelActive: {
    color: COLORS.teal,
  },
  completeDot: {
    position: 'absolute',
    top: 2,
    right: 6,
    width: 14,
    height: 14,
    borderRadius: 7,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.teal,
    borderWidth: 2,
    borderColor: COLORS.white,
  },
  modalSafeArea: {
    flex: 1,
    backgroundColor: COLORS.background,
  },
  legalSafeArea: {
    flex: 1,
    backgroundColor: COLORS.background,
  },
  legalModalContent: {
    paddingHorizontal: 22,
    paddingBottom: 36,
  },
  legalHero: {
    marginBottom: 18,
    padding: 22,
    borderWidth: 1.5,
    borderColor: '#DCE7FF',
    borderRadius: 28,
    backgroundColor: COLORS.bluePale,
    ...FLOATING_SHADOW,
  },
  legalHeroIcon: {
    width: 58,
    height: 58,
    marginBottom: 14,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.white,
  },
  legalTitle: {
    color: COLORS.ink,
    fontSize: 28,
    lineHeight: 33,
    fontWeight: '900',
    letterSpacing: -0.8,
  },
  legalSubtitle: {
    marginTop: 6,
    color: COLORS.muted,
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '600',
  },
  legalDate: {
    marginTop: 14,
    color: COLORS.blue,
    fontSize: 11,
    fontWeight: '900',
    letterSpacing: 0.8,
  },
  legalSection: {
    marginBottom: 12,
    padding: 16,
    borderWidth: 1.5,
    borderColor: COLORS.border,
    borderRadius: 22,
    backgroundColor: COLORS.surface,
    ...SOFT_SHADOW,
  },
  legalSectionTitle: {
    color: COLORS.ink,
    fontSize: 14,
    fontWeight: '900',
  },
  legalBodyText: {
    marginTop: 7,
    color: COLORS.muted,
    fontSize: 13,
    lineHeight: 20,
    fontWeight: '600',
  },
  modalKeyboard: {
    flex: 1,
  },
  modalContent: {
    paddingHorizontal: 22,
    paddingBottom: 35,
  },
  modalTopRow: {
    paddingTop: 8,
    marginBottom: 19,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  closeButton: {
    width: 40,
    height: 40,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.white,
    ...SOFT_SHADOW,
  },
  closeButtonPlaceholder: {
    width: 40,
  },
  modalStep: {
    paddingHorizontal: 11,
    paddingVertical: 7,
    borderRadius: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    backgroundColor: COLORS.tealPale,
  },
  modalStepText: {
    color: COLORS.teal,
    fontSize: 10,
    fontWeight: '900',
    letterSpacing: 0.8,
  },
  modalTitle: {
    color: COLORS.ink,
    fontSize: 31,
    fontWeight: '900',
    letterSpacing: -1,
  },
  modalSubtitle: {
    marginTop: 6,
    marginBottom: 25,
    color: COLORS.muted,
    fontSize: 15,
    lineHeight: 21,
  },
  inputGroup: {
    marginBottom: 19,
  },
  inputLabelRow: {
    marginBottom: 8,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
  },
  inputLabel: {
    color: COLORS.purpleDark,
    fontSize: 11,
    fontWeight: '900',
    letterSpacing: 0.9,
  },
  input: {
    minHeight: 55,
    paddingHorizontal: 16,
    borderWidth: 1.5,
    borderColor: '#E5DEF7',
    borderRadius: 19,
    color: '#4E5274',
    backgroundColor: '#FFFCF7',
    ...SOFT_SHADOW,
    fontSize: 16,
    fontWeight: '500',
  },
  inputMultiline: {
    minHeight: 93,
    paddingTop: 15,
    textAlignVertical: 'top',
  },
  lookupButton: {
    minHeight: 72,
    marginBottom: 17,
    padding: 13,
    borderRadius: 18,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.blue,
    ...FLOATING_SHADOW,
  },
  lookupButtonDisabled: {
    opacity: 0.72,
  },
  lookupButtonIcon: {
    width: 43,
    height: 43,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.2)',
  },
  lookupButtonCopy: {
    flex: 1,
    marginLeft: 12,
  },
  lookupButtonTitle: {
    color: COLORS.white,
    fontSize: 15,
    fontWeight: '900',
  },
  lookupButtonSubtitle: {
    marginTop: 3,
    color: '#EAF6FF',
    fontSize: 11,
    lineHeight: 15,
    fontWeight: '700',
  },
  lookupStatus: {
    marginTop: -5,
    marginBottom: 17,
    padding: 12,
    borderRadius: 14,
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
  },
  lookupStatusSuccess: {
    backgroundColor: COLORS.greenPale,
    borderWidth: 1,
    borderColor: '#D8F5E9',
  },
  lookupStatusSoft: {
    backgroundColor: COLORS.bluePale,
    borderWidth: 1,
    borderColor: '#DCE7FF',
  },
  lookupStatusText: {
    flex: 1,
    color: COLORS.ink,
    fontSize: 12,
    lineHeight: 17,
    fontWeight: '700',
  },
  spellingSuggestionCard: {
    marginTop: -5,
    marginBottom: 18,
    padding: 16,
    borderRadius: 24,
    backgroundColor: '#F7F2FF',
    borderWidth: 1.5,
    borderColor: '#D9CEFF',
    boxShadow: '0 16px 34px rgba(91, 77, 228, 0.14)',
    elevation: 5,
  },
  spellingSuggestionHeader: {
    marginBottom: 13,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
  },
  spellingSuggestionTitle: {
    color: COLORS.purpleDark,
    fontSize: 14,
    fontWeight: '900',
    letterSpacing: 0.1,
  },
  spellingSuggestionList: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  spellingSuggestionChip: {
    minHeight: 44,
    paddingHorizontal: 16,
    borderRadius: 18,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 9,
    backgroundColor: '#FFFCFF',
    borderWidth: 1.5,
    borderColor: '#D8CEFF',
    boxShadow: '0 9px 18px rgba(91, 77, 228, 0.1)',
    elevation: 3,
  },
  spellingSuggestionChipText: {
    color: COLORS.ink,
    fontSize: 14,
    fontWeight: '900',
  },
  lookupInfoCard: {
    marginBottom: 18,
    padding: 15,
    borderWidth: 1.5,
    borderColor: '#DCE7FF',
    borderRadius: 22,
    backgroundColor: '#F0FAFF',
    ...SOFT_SHADOW,
  },
  lookupInfoHeader: {
    marginBottom: 11,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
  },
  lookupInfoTitle: {
    color: '#5268C9',
    fontSize: 10,
    fontWeight: '900',
    letterSpacing: 0.9,
  },
  lookupInfoText: {
    marginTop: 10,
    color: '#5268C9',
    fontSize: 12,
    lineHeight: 18,
    fontWeight: '700',
  },
  historyCard: {
    marginTop: -2,
    marginBottom: 18,
    padding: 15,
    borderWidth: 1.5,
    borderColor: '#E3DAFF',
    borderRadius: 22,
    backgroundColor: COLORS.orangePale,
    ...SOFT_SHADOW,
  },
  historyTitle: {
    color: COLORS.purple,
    fontSize: 10,
    fontWeight: '900',
    letterSpacing: 0.9,
  },
  historyDetailRow: {
    marginTop: 8,
  },
  historyDetailLabel: {
    marginBottom: 4,
    color: COLORS.purple,
    fontSize: 9,
    fontWeight: '900',
    letterSpacing: 0.8,
  },
  historyText: {
    color: '#6E619C',
    fontSize: 12,
    lineHeight: 18,
    fontWeight: '700',
  },
  memoryTip: {
    marginBottom: 20,
    padding: 14,
    borderRadius: 15,
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
    backgroundColor: COLORS.purplePale,
    borderWidth: 1,
    borderColor: '#E4DCFF',
  },
  memoryTipIcon: {
    width: 31,
    height: 31,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.white,
  },
  memoryTipText: {
    flex: 1,
    color: '#5E4D9C',
    fontSize: 12,
    lineHeight: 18,
    fontWeight: '600',
  },
  authKeyboard: {
    flex: 1,
  },
  authContent: {
    flexGrow: 1,
    paddingHorizontal: 20,
    paddingBottom: 34,
  },
  authHero: {
    minHeight: 330,
    marginTop: 10,
    padding: 24,
    borderRadius: 38,
    overflow: 'hidden',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#DDE9FF',
    ...FLOATING_SHADOW,
  },
  authCloudOne: {
    position: 'absolute',
    width: 230,
    height: 230,
    borderRadius: 115,
    top: -48,
    right: -65,
    backgroundColor: '#FFEAF1',
    opacity: 0.82,
  },
  authCloudTwo: {
    position: 'absolute',
    width: 260,
    height: 190,
    borderRadius: 95,
    bottom: -55,
    left: -70,
    backgroundColor: '#E8FBF4',
    opacity: 0.86,
  },
  authLogo: {
    width: 72,
    height: 72,
    borderRadius: 26,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.purpleDark,
    borderWidth: 5,
    borderColor: 'rgba(255,255,255,0.7)',
    ...FLOATING_SHADOW,
  },
  authKicker: {
    marginTop: 18,
    color: COLORS.purpleDark,
    fontSize: 11,
    fontWeight: '900',
    letterSpacing: 1.4,
  },
  authTitle: {
    marginTop: 8,
    color: COLORS.ink,
    fontSize: 34,
    lineHeight: 38,
    fontWeight: '900',
    letterSpacing: -1,
    textAlign: 'center',
  },
  authSubtitle: {
    marginTop: 10,
    maxWidth: 320,
    color: '#5E6687',
    fontSize: 14,
    lineHeight: 21,
    fontWeight: '700',
    textAlign: 'center',
  },
  authCard: {
    marginTop: -34,
    marginHorizontal: 8,
    padding: 18,
    borderRadius: 30,
    backgroundColor: 'rgba(255,255,255,0.94)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.75)',
    ...FLOATING_SHADOW,
  },
  oauthGrid: {
    flexDirection: 'row',
    gap: 10,
    marginBottom: 14,
  },
  oauthButton: {
    flex: 1,
    minHeight: 58,
    paddingHorizontal: 12,
    borderRadius: 20,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    backgroundColor: COLORS.white,
    borderWidth: 1.5,
    borderColor: '#E5E8F4',
    ...SOFT_SHADOW,
  },
  oauthIconBadge: {
    width: 34,
    height: 34,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.bluePale,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.82)',
  },
  oauthGoogleLogo: {
    width: 24,
    height: 24,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.white,
    overflow: 'hidden',
    position: 'relative',
  },
  oauthGoogleClip: {
    position: 'absolute',
    width: 12,
    height: 12,
    overflow: 'hidden',
  },
  oauthGoogleClipTopLeft: {
    top: 0,
    left: 0,
  },
  oauthGoogleClipTopRight: {
    top: 0,
    right: 0,
  },
  oauthGoogleClipBottomLeft: {
    bottom: 0,
    left: 0,
  },
  oauthGoogleClipBottomRight: {
    right: 0,
    bottom: 0,
  },
  oauthGoogleIcon: {
    position: 'absolute',
    width: 22,
    height: 22,
  },
  oauthGoogleIconTopLeft: {
    top: 1,
    left: 1,
  },
  oauthGoogleIconTopRight: {
    top: 1,
    right: 1,
  },
  oauthGoogleIconBottomLeft: {
    bottom: 1,
    left: 1,
  },
  oauthGoogleIconBottomRight: {
    right: 1,
    bottom: 1,
  },
  oauthGoogleCrossbar: {
    position: 'absolute',
    right: 1.5,
    top: 10,
    width: 10,
    height: 4,
    borderRadius: 2,
    backgroundColor: '#4285F4',
  },
  oauthMicrosoftLogo: {
    width: 21,
    height: 21,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 2,
  },
  oauthMicrosoftTile: {
    width: 9.5,
    height: 9.5,
    borderRadius: 1.8,
  },
  oauthButtonText: {
    color: COLORS.ink,
    fontSize: 14,
    fontWeight: '900',
  },
  authDividerRow: {
    marginTop: 2,
    marginBottom: 17,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  authDividerLine: {
    flex: 1,
    height: 1,
    backgroundColor: COLORS.border,
  },
  authDividerText: {
    color: COLORS.muted,
    fontSize: 11,
    fontWeight: '900',
    letterSpacing: 0.6,
    textTransform: 'uppercase',
  },
  authFieldGroup: {
    marginBottom: 14,
  },
  authFieldLabel: {
    marginBottom: 8,
    color: COLORS.muted,
    fontSize: 10,
    fontWeight: '900',
    letterSpacing: 1,
  },
  authInputWrap: {
    minHeight: 58,
    paddingHorizontal: 15,
    borderRadius: 19,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    backgroundColor: '#F6F8FF',
    borderWidth: 1.5,
    borderColor: '#E3E8FF',
  },
  authInput: {
    flex: 1,
    color: COLORS.ink,
    fontSize: 15,
    fontWeight: '700',
  },
  forgotLink: {
    alignSelf: 'flex-end',
    marginBottom: 14,
  },
  authPasswordHint: {
    marginTop: -5,
    marginBottom: 13,
    color: COLORS.muted,
    fontSize: 12,
    lineHeight: 17,
    fontWeight: '700',
  },
  forgotLinkText: {
    color: COLORS.blue,
    fontSize: 13,
    fontWeight: '900',
  },
  authPrimaryButton: {
    minHeight: 58,
    borderRadius: 20,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: COLORS.purpleDark,
    ...FLOATING_SHADOW,
  },
  authPrimaryButtonDisabled: {
    opacity: 0.72,
  },
  authPrimaryButtonText: {
    color: COLORS.white,
    fontSize: 15,
    fontWeight: '900',
    letterSpacing: 0.2,
  },
  authSwitchRow: {
    marginTop: 16,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 6,
  },
  authSwitchText: {
    color: COLORS.muted,
    fontSize: 13,
    fontWeight: '700',
  },
  authSwitchAction: {
    color: COLORS.purpleDark,
    fontSize: 13,
    fontWeight: '900',
  },
  authNoteCard: {
    marginTop: 16,
    marginHorizontal: 8,
    padding: 14,
    borderRadius: 22,
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
    backgroundColor: COLORS.bluePale,
    borderWidth: 1,
    borderColor: '#D7E5FF',
  },
  authNoteText: {
    flex: 1,
    color: '#5268A8',
    fontSize: 12,
    lineHeight: 18,
    fontWeight: '700',
  },
  verificationCard: {
    marginBottom: 14,
    padding: 14,
    borderRadius: 22,
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 11,
    backgroundColor: '#F0FAFF',
    borderWidth: 1.5,
    borderColor: '#D8ECFF',
    ...SOFT_SHADOW,
  },
  verificationIcon: {
    width: 40,
    height: 40,
    borderRadius: 15,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.bluePale,
  },
  verificationCopy: {
    flex: 1,
  },
  verificationTitle: {
    color: COLORS.ink,
    fontSize: 14,
    fontWeight: '900',
  },
  verificationText: {
    marginTop: 4,
    color: COLORS.muted,
    fontSize: 12,
    lineHeight: 17,
    fontWeight: '700',
  },
  verificationResendButton: {
    alignSelf: 'flex-start',
    marginTop: 10,
    minHeight: 35,
    paddingHorizontal: 13,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.white,
    borderWidth: 1,
    borderColor: '#CFE0FF',
  },
  verificationResendText: {
    color: COLORS.blue,
    fontSize: 12,
    fontWeight: '900',
  },
  verificationDismiss: {
    width: 28,
    height: 28,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.white,
  },
  accountCard: {
    marginTop: 18,
    padding: 16,
    borderRadius: 26,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    backgroundColor: COLORS.white,
    borderWidth: 1,
    borderColor: COLORS.border,
    ...SOFT_SHADOW,
  },
  accountAvatar: {
    width: 50,
    height: 50,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.purplePale,
  },
  accountAvatarText: {
    color: COLORS.purpleDark,
    fontSize: 20,
    fontWeight: '900',
  },
  accountCopy: {
    flex: 1,
  },
  accountLabel: {
    color: COLORS.muted,
    fontSize: 9,
    fontWeight: '900',
    letterSpacing: 0.9,
  },
  accountName: {
    marginTop: 3,
    color: COLORS.ink,
    fontSize: 16,
    fontWeight: '900',
  },
  accountEmail: {
    marginTop: 2,
    color: COLORS.muted,
    fontSize: 12,
    fontWeight: '700',
  },
  logoutButton: {
    minHeight: 40,
    paddingHorizontal: 12,
    borderRadius: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: COLORS.redPale,
  },
  logoutButtonText: {
    color: COLORS.red,
    fontSize: 12,
    fontWeight: '900',
  },
  deleteAccountCard: {
    marginTop: 12,
    padding: 16,
    borderRadius: 26,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    backgroundColor: '#FFF7F8',
    borderWidth: 1,
    borderColor: '#FFD7DE',
    ...SOFT_SHADOW,
  },
  deleteAccountIcon: {
    width: 46,
    height: 46,
    borderRadius: 17,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.redPale,
  },
  deleteAccountCopy: {
    flex: 1,
  },
  deleteAccountLabel: {
    color: COLORS.red,
    fontSize: 9,
    fontWeight: '900',
    letterSpacing: 0.9,
  },
  deleteAccountTitle: {
    marginTop: 3,
    color: COLORS.ink,
    fontSize: 15,
    fontWeight: '900',
  },
  deleteAccountText: {
    marginTop: 4,
    color: COLORS.muted,
    fontSize: 12,
    lineHeight: 17,
    fontWeight: '700',
  },
  deleteAccountButton: {
    minHeight: 40,
    paddingHorizontal: 13,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.red,
  },
  deleteAccountButtonText: {
    color: COLORS.white,
    fontSize: 12,
    fontWeight: '900',
  },
});
